@NewShoreTest_HostAddress = http://localhost:5157

Put {{NewShoreTest_HostAddress}}/api/NewShoreApi
Accept: application/json
Content-Type: application/json

{
  "origin": "MZL",
  "destination": "BCN"
}

###
